(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  function waitForClient(){return new Promise(resolve=>{if(window.korgeoAdminSupabase)return resolve(window.korgeoAdminSupabase);const t=setInterval(()=>{if(window.korgeoAdminSupabase){clearInterval(t);resolve(window.korgeoAdminSupabase);}},50);setTimeout(()=>{clearInterval(t);resolve(window.korgeoAdminSupabase||null);},4000);});}
  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
  function fmt(iso){return iso?new Intl.DateTimeFormat('ko-KR',{dateStyle:'short',timeStyle:'short'}).format(new Date(iso)):'-';}
  function addStyles(){const st=document.createElement('style');st.textContent='.ops-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.ops-box{background:#f8fbff;border:1px solid #d9e6f0;border-radius:12px;padding:13px}.ops-box h3{margin:0 0 9px}.ops-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:8px 0}.ops-row input[type=text]{flex:1;min-width:180px}.ops-table{width:100%;border-collapse:collapse;font-size:.8rem}.ops-table th,.ops-table td{padding:7px;border-bottom:1px solid #e4edf4}.pill{display:inline-block;padding:2px 7px;border-radius:999px;background:#e8f0f8;font-size:.72rem;font-weight:800}.traffic-bars{display:grid;gap:7px}.traffic-line{display:grid;grid-template-columns:70px 1fr 45px;gap:8px;align-items:center}.traffic-bar{height:10px;border-radius:999px;background:#dce8f2;overflow:hidden}.traffic-fill{height:100%;background:#1769aa}.audit{max-height:340px;overflow:auto}.audit-item{padding:8px 0;border-bottom:1px solid #e4edf4}.audit-item b{font-size:.82rem}.audit-item small{display:block;color:#637a8e;margin-top:3px}.ops-note{font-size:.78rem;color:#637a8e;line-height:1.45}';document.head.appendChild(st);}
  function buildUI(){if($('opsPanel'))return;const app=$('app');if(!app)return;const sec=document.createElement('section');sec.id='opsPanel';sec.className='card';sec.innerHTML=`<h2>운영 제어</h2><div class="ops-grid"><div class="ops-box"><h3>사이트 상태</h3><div class="ops-row"><label><input id="regEnabled" type="checkbox"> 신규 회원가입 허용</label></div><div class="ops-row"><label><input id="maintEnabled" type="checkbox"> 점검 모드 표시</label></div><input id="maintText" type="text" maxlength="500" placeholder="점검 안내 문구"><div class="ops-row"><button id="saveRuntimeBtn">운영 설정 저장</button></div><p id="runtimeStatus" class="status"></p><p class="ops-note">회원가입 OFF는 본/퀴즈 페이지 가입 버튼을 막고 서버 가입 슬롯 RPC에서도 거절해.</p></div><div class="ops-box"><h3>사용자 도구</h3><input id="userSearch" type="text" placeholder="아이디 검색"><div class="ops-row"><button id="exportUsersBtn" class="secondary">사용자 CSV 내보내기</button></div><p id="userSearchStatus" class="ops-note"></p></div></div><div class="ops-grid" style="margin-top:12px"><div class="ops-box"><h3>최근 7일 트래픽</h3><div id="traffic7d" class="traffic-bars"></div></div><div class="ops-box"><h3>관리자 작업 로그</h3><div id="auditLog" class="audit"></div></div></div>`;const userCard=$('users')?.closest('.card');app.insertBefore(sec,userCard||null);}
  async function loadRuntime(sb){const {data,error}=await sb.rpc('get_public_runtime_config');if(error)throw error;const v=data||{};$('regEnabled').checked=v.registration_enabled!==false;$('maintEnabled').checked=Boolean(v.maintenance_enabled);$('maintText').value=v.maintenance_text||'';}
  async function saveRuntime(sb){$('runtimeStatus').textContent='저장 중…';const {data,error}=await sb.rpc('admin_set_runtime_config',{p_registration_enabled:$('regEnabled').checked,p_maintenance_enabled:$('maintEnabled').checked,p_maintenance_text:$('maintText').value.trim()});if(error){$('runtimeStatus').textContent='실패: '+error.message;$('runtimeStatus').className='status error';return;}$('runtimeStatus').textContent='저장 완료';$('runtimeStatus').className='status ok';}
  async function loadTraffic(sb){const {data,error}=await sb.rpc('admin_usage_7d');if(error)throw error;const rows=data||[];const max=Math.max(1,...rows.map(r=>Number(r.total_visitors)||0));$('traffic7d').innerHTML=rows.map(r=>`<div class="traffic-line"><span>${esc(r.day)}</span><div class="traffic-bar"><div class="traffic-fill" style="width:${Math.round((Number(r.total_visitors)||0)/max*100)}%"></div></div><b>${Number(r.total_visitors)||0}</b></div>`).join('');}
  async function loadAudit(sb){const {data,error}=await sb.rpc('admin_recent_audit',{p_limit:100});if(error)throw error;const rows=data||[];$('auditLog').innerHTML=rows.length?rows.map(r=>`<div class="audit-item"><b>${esc(r.action)} <span class="pill">${esc(r.admin_login||'admin')}</span></b><small>${fmt(r.created_at)}${r.target_login?' · 대상 '+esc(r.target_login):''}</small></div>`).join(''):'<p class="ops-note">아직 작업 기록이 없어.</p>';}
  function filterUsers(q){q=String(q||'').trim().toLowerCase();const rows=[...document.querySelectorAll('#users tr')];let shown=0;rows.forEach(tr=>{const text=(tr.firstChild?.textContent||'').toLowerCase();const hit=!q||text.includes(q);tr.style.display=hit?'':'none';if(hit)shown++;});$('userSearchStatus').textContent=`표시 ${shown}명`}
  function exportUsers(){const rows=window.korgeoAdminUsers||[];if(!rows.length)return;const cols=['login_id','created_at','last_sign_in_at','wrong_count','has_progress','is_admin'];const csv=[cols.join(','),...rows.map(r=>cols.map(k=>'"'+String(r[k]??'').replace(/"/g,'""')+'"').join(','))].join('\r\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='korgeo-users-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  (async()=>{addStyles();buildUI();const sb=await waitForClient();if(!sb)return;const ready=window.korgeoAdminReady?await window.korgeoAdminReady:false;if(!ready)return;try{await Promise.all([loadRuntime(sb),loadTraffic(sb),loadAudit(sb)]);}catch(e){console.warn('운영 패널 로드 실패',e);} $('saveRuntimeBtn').onclick=()=>saveRuntime(sb);$('userSearch').oninput=e=>filterUsers(e.target.value);$('exportUsersBtn').onclick=exportUsers;window.addEventListener('korgeo-admin-users',()=>filterUsers($('userSearch').value));const old=window.korgeoAdminReload;if(old){window.korgeoAdminReload=async()=>{await old();await Promise.all([loadRuntime(sb),loadTraffic(sb),loadAudit(sb)]);};}})();
})();
